(function(){var h={},mt={},c={id:"a2647413544f5a04f00da7eee0d5e200",dm:["liepin.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:4216552,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,r=!1;mt.h={};mt.h.xa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.za=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,g){var e;g.D&&(e=new Date,e.setTime(e.getTime()+g.D));document.cookie=a+"="+b+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(e?"; expires="+e.toGMTString():"")+(g.La?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.m={};mt.m.ka=function(a){return document.getElementById(a)};mt.m.la=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return q};
(mt.m.V=function(){function a(){if(!a.w){a.w=p;for(var b=0,k=e.length;b<k;b++)e[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var g=r,e=[],k;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,r);a()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),a())});(function(){if(!g)if(g=p,"complete"===document.readyState)a.w=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
k,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",k);window.attachEvent("onload",a);var e=r;try{e=window.frameElement==q}catch(n){}document.documentElement.doScroll&&e&&b()}})();return function(b){a.w?b():e.push(b)}}()).w=r;mt.event={};mt.event.c=function(a,b,g){a.attachEvent?a.attachEvent("on"+b,function(e){g.call(a,e)}):a.addEventListener&&a.addEventListener(b,g,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.o={};mt.o.parse=function(){return(new Function('return (" + source + ")'))()};
mt.o.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var e=g[a];if(e)return e;e=a.charCodeAt();return"\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===q)return"null";if(e instanceof Array){var k=["["],g=e.length,n,f,d;for(f=0;f<g;f++)switch(d=e[f],typeof d){case "undefined":case "function":case "unknown":break;default:n&&k.push(","),k.push(mt.o.stringify(d)),n=1}k.push("]");return k.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';n=["{"];f=mt.o.stringify;for(g in e)if(Object.prototype.hasOwnProperty.call(e,g))switch(d=
e[g],typeof d){case "undefined":case "unknown":case "function":break;default:k&&n.push(","),k=1,n.push(f(g)+":"+f(d))}n.push("}");return n.join("")}}}();mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ia=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ka=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.B=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,b,g){var e=new Date;e.setTime(e.getTime()+g||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.B()&&(mt.localStorage.f.expires=e.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),g=a.substring(0,b)-0;if(g&&g>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.B())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(e){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.B())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(g){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.L={};mt.L.log=function(a,b){var g=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=q;g=window[e]=q;b&&b(a)};g.src=a};mt.M={};
mt.M.ra=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.M.Ea=function(a,b,g,e,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+e+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+e+'" src="'+b+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.i=function(a,b){var g=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return g?g[3]:q};mt.url.Ga=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.oa=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.Q=function(a){return(a=mt.url.oa(a))?a.replace(/:\d+$/,""):a};mt.url.Fa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.q={Ha:"http://tongji.baidu.com/hm-web/welcome/ico",J:"hm.baidu.com/hm.gif",$:"baidu.com",ua:"hmmd",va:"hmpl",ta:"hmkw",sa:"hmci",wa:"hmsr",p:0,k:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Ja:0,ea:6E5,fa:10,N:1024,da:1,j:2147483647,X:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={l:{},c:function(a,g){this.l[a]=this.l[a]||[];this.l[a].push(g)},s:function(a,g){this.l[a]=this.l[a]||[];for(var e=this.l[a].length,k=0;k<e;k++)this.l[a][k](g)}};return h.n=a})();
(function(){function a(a,e){var k=document.createElement("script");k.charset="utf-8";b.e(e,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=q,e()}:k.onload=function(){e()});k.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(k,m)}var b=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?g.set("Hm_from_"+c.id,a):b.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?g.get("Hm_from_"+c.id):b.get("Hm_from_"+c.id))||"";return a}var b=mt.localStorage,g=mt.sessionStorage;return h.O=a})();
(function(){var a=mt.m,b=mt.event,g=mt.h,e=h.q,k=[],m={Y:function(){c.ctrk&&(b.c(document,"mouseup",m.ca()),b.c(window,"unload",function(){m.z()}),setInterval(function(){m.z()},e.ea))},ca:function(){return function(a){a=m.ma(a);if(""!==a){var f=(e.protocol+"//"+e.J+"?"+h.b.W().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;f+(e.j+"").length>e.N||(f+encodeURIComponent(k.join(",")+(k.length?",":"")).length+(e.j+"").length>e.N&&m.z(),k.push(a),(k.length>=e.fa||/t:a/.test(a))&&m.z())}}},
ma:function(b){if(0===e.da){var f=b.target||b.srcElement,d=f.tagName.toLowerCase();if("embed"==d||"object"==d)return""}g.xa?(f=Math.max(document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),d=b.clientX+d,f=b.clientY+f):(d=b.pageX,f=b.pageY);var l=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:d-=l/2;break;case 2:d-=l}d="{x:"+d+",y:"+f+",";f=b.target||b.srcElement;
return d=(b="a"==f.tagName.toLowerCase()?f:a.la(f))?d+("t:a,u:"+encodeURIComponent(b.href)+"}"):d+"t:b}"},z:function(){0!==k.length&&(h.b.a.et=2,h.b.a.ep="["+k.join(",")+"]",h.b.g(),k=[])}};h.n.c("pv-b",m.Y);return m})();
(function(){var a=mt.m,b=h.q,g=h.load,e=h.O;h.n.c("pv-b",function(){c.rec&&a.V(function(){for(var k=0,m=c.rp.length;k<m;k++){var n=c.rp[k][0],f=c.rp[k][1],d=a.ka("hm_t_"+n);if(f&&!(2==f&&!d||d&&""!==d.innerHTML))d="",d=Math.round(Math.random()*b.j),d=4==f?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+n,"rnd="+d].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+n,"from="+e(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
d].join("&"),g(d)}})})})();(function(){var a=h.q,b=h.load,g=h.O;h.n.c("pv-b",function(){if(c.trust&&c.vcard){var e=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+g(),"rnd="+Math.round(Math.random()*a.j)].join("&");b(e)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.C.pa()+","+h.C.na();h.b.g()}}function b(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);f="undefined"==typeof a?p:a;if((!n||!d)&&f&&l)u=p,s=+new Date;else if(n&&d&&(!f||!l))u=r,t+=+new Date-s;n=f;d=l;x=setTimeout(b,100)}function g(d){var a=document,f="";if(d in a)f=d;else for(var l=["webkit","ms","moz","o"],s=0;s<l.length;s++){var b=l[s]+d.charAt(0).toUpperCase()+d.slice(1);if(b in a){f=
b;break}}return f}function e(d){if(!("focus"==d.type||"blur"==d.type)||!(d.target&&d.target!=window))l="focus"==d.type||"focusin"==d.type?p:r,b()}var k=mt.event,m=h.n,n=p,f=p,d=p,l=p,v=+new Date,s=v,t=0,u=p,w=g("visibilityState"),y=g("hidden"),x;b();(function(){var d=w.replace(/[vV]isibilityState/,"visibilitychange");k.c(document,d,b);k.c(window,"pageshow",b);k.c(window,"pagehide",b);"object"==typeof document.onfocusin?(k.c(document,"focusin",e),k.c(document,"focusout",e)):(k.c(window,"focus",e),
k.c(window,"blur",e))})();h.C={pa:function(){return+new Date-v},na:function(){return u?+new Date-s+t:t}};m.c("pv-b",function(){k.c(window,"unload",a())});return h.C})();
(function(){function a(d){for(var f in d)if({}.hasOwnProperty.call(d,f)){var b=d[f];e.e(b,"Object")||e.e(b,"Array")?a(b):d[f]=String(b)}}function b(d){return d.replace?d.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):d}var g=mt.L,e=mt.lang,k=mt.o,m=h.q,n=h.n,f={R:q,r:[],A:0,S:r,init:function(){f.d=0;f.R={push:function(){f.I.apply(f,arguments)}};n.c("pv-b",function(){f.ga();f.ha()});n.c("pv-d",f.ia);n.c("stag-b",function(){h.b.a.api=f.d||f.A?f.d+"_"+f.A:""});n.c("stag-d",function(){h.b.a.api=
0;f.d=0;f.A=0})},ga:function(){var d=window._hmt;if(d&&d.length)for(var a=0;a<d.length;a++){var b=d[a];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(f.d|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))f.d|=2,window._bdhm_autoPageview=b}}},ha:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var d=window._hmt;if(d&&d.length)for(var a=0,b=d.length;a<b;a++)e.e(d[a],
"Array")&&"_trackEvent"!==d[a][0]&&"_trackRTEvent"!==d[a][0]?f.I(d[a]):f.r.push(d[a]);window._hmt=f.R}},ia:function(){if(0<f.r.length)for(var d=0,a=f.r.length;d<a;d++)f.I(f.r[d]);f.r=q},I:function(d){if(e.e(d,"Array")){var a=d[0];if(f.hasOwnProperty(a)&&e.e(f[a],"Function"))f[a](d)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){f.d|=4;h.b.a.et=0;h.b.a.ep="";h.b.G?(h.b.a.nv=0,h.b.a.st=4):h.b.G=p;var b=h.b.a.u,e=h.b.a.su;h.b.a.u=m.protocol+"//"+document.location.host+
a[1];f.S||(h.b.a.su=document.location.href);h.b.g();h.b.a.u=b;h.b.a.su=e}},_trackEvent:function(a){2<a.length&&(f.d|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.g())},_setCustomVar:function(a){if(!(4>a.length)){var e=a[1],g=a[4]||3;if(0<e&&6>e&&0<g&&4>g){f.A++;for(var s=(h.b.a.cv||"*").split("!"),t=s.length;t<e-1;t++)s.push("*");s[e-1]=g+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.ya("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?m.protocol+"//"+window.location.host+a[1]:a[1],f.S=p)},_trackOrder:function(d){d=d[1];e.e(d,"Object")&&(a(d),f.d|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=k.stringify(d),h.b.g())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.d|=32,h.b.a.et=93,h.b.a.ep=a,h.b.g()},_trackRTPageview:function(d){d=
d[1];e.e(d,"Object")&&(a(d),d=k.stringify(d),512>=encodeURIComponent(d).length&&(f.d|=64,h.b.a.rt=d))},_trackRTEvent:function(d){d=d[1];if(e.e(d,"Object")){a(d);d=encodeURIComponent(k.stringify(d));var b=function(a){var d=h.b.a.rt;f.d|=128;h.b.a.et=90;h.b.a.rt=a;h.b.g();h.b.a.rt=d},g=d.length;if(900>=g)b.call(this,d);else for(var g=Math.ceil(g/900),s="block|"+Math.round(Math.random()*m.j).toString(16)+"|"+g+"|",t=[],u=0;u<g;u++)t.push(u),t.push(d.substring(900*u,900*u+900)),b.call(this,s+t.join("|")),
t=[]}},_setUserId:function(a){a=a[1];if(e.e(a,"String")||e.e(a,"Number")){var b=h.b.F(),k="hm-"+h.b.a.v;f.U=f.U||Math.round(Math.random()*m.j);g.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(b)+"&ac="+encodeURIComponent(a)+"&v="+k+"&li="+f.U+"&rnd="+Math.round(Math.random()*m.j))}}};f.init();h.aa=f;return h.aa})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.G=r,this.init())}var b=mt.url,g=mt.L,e=mt.M,k=mt.lang,m=mt.cookie,n=mt.h,f=mt.localStorage,d=mt.sessionStorage,l=h.q,v=h.n;a.prototype={H:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length==a.length},T:function(a,d){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(d)},t:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.T(a,c.dm[d]))return p}else{var f=b.Q(a);if(f&&this.H(f,c.dm[d]))return p}return r},F:function(){for(var a=document.location.hostname,d=0,b=c.dm.length;d<b;d++)if(this.H(a,c.dm[d]))return c.dm[d].replace(/(:\d+)?[\/\?#].*/,"");return a},P:function(){for(var a=0,d=c.dm.length;a<d;a++){var b=c.dm[a];if(-1<b.indexOf("/")&&this.T(document.location.href,b))return b.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},qa:function(){if(!document.referrer)return l.k-l.p>c.vdur?1:4;var a=
r;this.t(document.referrer)&&this.t(document.location.href)?a=p:(a=b.Q(document.referrer),a=this.H(a||"",document.location.hostname));return a?l.k-l.p>c.vdur?1:4:3},getData:function(a){try{return m.get(a)||d.get(a)||f.get(a)}catch(b){}},setData:function(a,b,e){try{m.set(a,b,{domain:this.F(),path:this.P(),D:e}),e?f.set(a,b,e):d.set(a,b)}catch(g){}},ya:function(a){try{m.set(a,"",{domain:this.F(),path:this.P(),D:-1}),d.remove(a),f.remove(a)}catch(b){}},Ca:function(){var a,d,b,f,e;l.p=this.getData("Hm_lpvt_"+
c.id)||0;13==l.p.length&&(l.p=Math.round(l.p/1E3));d=this.qa();a=4!=d?1:0;if(b=this.getData("Hm_lvt_"+c.id)){f=b.split(",");for(e=f.length-1;0<=e;e--)13==f[e].length&&(f[e]=""+Math.round(f[e]/1E3));for(;2592E3<l.k-f[0];)f.shift();e=4>f.length?2:3;for(1===a&&f.push(l.k);4<f.length;)f.shift();b=f.join(",");f=f[f.length-1]}else b=l.k,f="",e=1;this.setData("Hm_lvt_"+c.id,b,c.age);this.setData("Hm_lpvt_"+c.id,l.k);b=l.k==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.t(document.location.href)&&
(""===document.referrer||this.t(document.referrer)))a=0,d=4;this.a.nv=a;this.a.st=d;this.a.cc=b;this.a.lt=f;this.a.lv=e},W:function(){for(var a=[],d=0,b=l.X.length;d<b;d++){var f=l.X[d],e=this.a[f];"undefined"!=typeof e&&""!==e&&a.push(f+"="+encodeURIComponent(e))}d=this.a.et;this.a.rt&&(0===d?a.push("rt="+encodeURIComponent(this.a.rt)):90===d&&a.push("rt="+this.a.rt));return a.join("&")},Da:function(){this.Ca();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=n.za;this.a.cl=n.colorDepth+"-bit";
this.a.ln=n.language;this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=e.ra();this.a.v="1.0.83";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.i(a,l.ua)||"";this.a.cp=b.i(a,l.va)||"";this.a.cw=b.i(a,l.ta)||"";this.a.ci=b.i(a,l.sa)||"";this.a.cf=b.i(a,l.wa)||""},init:function(){try{this.Da(),0===this.a.nv?this.Ba():this.K(".*"),h.b=this,this.ba(),
v.s("pv-b"),this.Aa()}catch(a){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(a.name));d.push("m="+encodeURIComponent(a.message));d.push("r="+encodeURIComponent(document.referrer));g.log(l.protocol+"//"+l.J+"?"+d.join("&"))}},Aa:function(){function a(){v.s("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.G=p,this.a.et=0,this.a.ep="",this.g(a)):a()},g:function(a){var d=this;d.a.rnd=Math.round(Math.random()*l.j);v.s("stag-b");var b=l.protocol+"//"+
l.J+"?"+d.W();v.s("stag-d");d.Z(b);g.log(b,function(b){d.K(b);k.e(a,"Function")&&a.call(d)})},ba:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),f=-1<document.referrer.indexOf(l.$)?p:r,e=b.i(a,"jn"),g=/^heatlink$|^select$/.test(e);a&&(d.test(a)&&f&&g)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+e+".js?"+this.a.rnd),e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(a,
e))},Z:function(a){var b=d.get("Hm_unsent_"+c.id)||"",f=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+f)+(b?","+b:"");d.set("Hm_unsent_"+c.id,b)},K:function(a){var b=d.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?d.set("Hm_unsent_"+c.id,b):d.remove("Hm_unsent_"+c.id))},Ba:function(){var a=this,b=d.get("Hm_unsent_"+
c.id);if(b)for(var b=b.split(","),f=function(d){g.log(l.protocol+"//"+decodeURIComponent(d).replace(/^https?:\/\//,""),function(d){a.K(d)})},e=0,k=b.length;e<k;e++)f(b[e])}};return new a})();
(function(){var a=mt.m,b=mt.event,g=mt.url,e=mt.o;try{if(window.performance&&performance.timing){var k=+new Date,m=function(a){var d=performance.timing,b=d[a+"Start"]?d[a+"Start"]:0;a=d[a+"End"]?d[a+"End"]:0;return{start:b,end:a,value:0<a-b?a-b:0}},n=q;a.V(function(){n=+new Date});var f=function(){var a,d,b;b=m("navigation");d=m("request");b={netAll:d.start-b.start,netDns:m("domainLookup").value,netTcp:m("connect").value,srv:m("response").start-d.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,
loadEvent:m("loadEvent").end-b.start};a=document.referrer;var f=q;d=q;if("www.baidu.com"===(a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[])[2])f=g.i(a,"qid"),d=g.i(a,"click_t");a=f;b.qid=a!=q?a:"";d!=q?(b.bdDom=n?n-d:0,b.bdRun=k-d):(b.bdDom=0,b.bdRun=0);h.b.a.et=87;h.b.a.ep=e.stringify(b);h.b.g()};b.c(window,"load",function(){setTimeout(f,500)})}}catch(d){}})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a=function(a){if(a.item){for(var d=a.length,b=Array(d);d--;)b[d]=a[d];return b}return[].slice.call(a)},b={click:function(){for(var b=[],d=a(document.getElementsByTagName("a")),d=[].concat.apply(d,a(document.getElementsByTagName("area"))),e=/openZoosUrl\(/,g=0,k=d.length;g<k;g++)e.test(d[g].getAttribute("onclick"))&&b.push(d[g]);return b}},g=function(a,d){for(var b in a)if(a.hasOwnProperty(b)&&d.call(a,b,a[b])===r)return r},e=function(a,
d){return Object.prototype.toString.call(a)==="[object "+d+"]"};window._hmt=window._hmt||[];var k,m="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,d){if(k===d){window._hmt.push(["_trackPageview",m+a]);for(var b=+new Date;500>=+new Date-b;);return r}if(e(d,"Array")||e(d,"NodeList"))for(var b=0,g=d.length;b<g;b++)if(k===d[b]){window._hmt.push(["_trackPageview",m+a+"/"+(b+1)]);for(b=+new Date;500>=+new Date-b;);return r}};(function(a,d,b){a.addEventListener?a.addEventListener(d,b,p):a.attachEvent&&
a.attachEvent("on"+d,b)})(document,"click",function(a){a=a||window.event;k=a.target||a.srcElement;var d={};for(g(b,function(a,b){d[a]=e(b,"Function")?b():document.getElementById(b)});k&&k!==document&&g(d,n)!==r;)k=k.parentNode})}})();})();
